(function(){
'use strict';
var board=document.getElementById('board'),columnsEl=document.getElementById('columns'),leftEl=document.getElementById('leftReserve'),rightEl=document.getElementById('rightReserve');
var fruitMap={};SunnyFruitsData.forEach(function(f){fruitMap[f.id]=f;});
function fruitArt(id){var f=fruitMap[id],art=document.createElement('div');art.className='fruit-art';art.setAttribute('role','img');art.setAttribute('aria-label',f.name);art.style.backgroundImage='url("'+SunnyFruitSheets[f.sheet]+'")';art.style.backgroundPosition=(f.col*20)+'% '+(f.row*20)+'%';return art;}
function tokenEl(id,pos,index,isTop){var el=document.createElement('div');el.className='token'+(isTop?' top':'');el.dataset.source=String(pos);el.dataset.index=index;el.dataset.fruit=id;el.style.bottom='calc('+index+' * (var(--token) + 2px) + 7px)';el.appendChild(fruitArt(id));return el;}
function render(state,handlers){columnsEl.innerHTML='';for(var i=0;i<state.columns.length;i++){var col=document.createElement('div');col.className='column'+(state.columns[i].length===4?' blocker':'');col.dataset.pos=String(i);state.columns[i].forEach(function(id,idx){var t=tokenEl(id,i,idx,idx===state.columns[i].length-1);if(idx===state.columns[i].length-1&&handlers)t.addEventListener('pointerdown',handlers.pointerDown);col.appendChild(t);});columnsEl.appendChild(col);}renderReserve(leftEl,state.left,'L',handlers);renderReserve(rightEl,state.right,'R',handlers);requestAnimationFrame(fitBoard);}
function renderReserve(el,id,pos,handlers){Array.from(el.querySelectorAll('.token')).forEach(function(x){x.remove();});if(id){var t=tokenEl(id,pos,0,true);if(handlers)t.addEventListener('pointerdown',handlers.pointerDown);el.appendChild(t);}}
function fitBoard(){var wrap=document.getElementById('boardWrap'),n=columnsEl.children.length;if(!n)return;var ww=wrap.clientWidth-8,hh=wrap.clientHeight-8;var token=Math.max(42,Math.min(72,Math.floor((ww-125)/(n+2)-5)));var laneW=token+8,gap=Math.max(3,Math.min(10,Math.floor(token*.12))),laneH=Math.min(hh-75,token*4+26);board.style.setProperty('--token',token+'px');board.style.setProperty('--laneW',laneW+'px');board.style.setProperty('--reserveW',laneW+'px');board.style.setProperty('--gap',gap+'px');board.style.setProperty('--laneH',laneH+'px');board.style.transform='scale(1)';var bw=board.scrollWidth,bh=board.scrollHeight,scale=Math.min(1,ww/bw,hh/bh);if(scale<1)board.style.transform='scale('+scale+')';}
function clearHighlights(){document.querySelectorAll('.drop-ok,.drop-bad,.hint,.selected').forEach(function(e){e.classList.remove('drop-ok','drop-bad','hint','selected');});}
function elementForPos(pos){if(pos==='L')return leftEl;if(pos==='R')return rightEl;return columnsEl.querySelector('[data-pos="'+pos+'"]');}
function highlightDest(pos,ok){var e=elementForPos(pos);if(e)e.classList.add(ok?'drop-ok':'drop-bad');}
function hint(move){clearHighlights();var src=elementForPos(move.from),dst=elementForPos(move.to);if(src){var t=src.querySelector('.token.top');if(t)t.classList.add('hint');}if(dst)dst.classList.add('hint');setTimeout(clearHighlights,2200);}
window.SunnyRenderer={render:render,fitBoard:fitBoard,clearHighlights:clearHighlights,elementForPos:elementForPos,highlightDest:highlightDest,fruitMap:fruitMap,fruitArt:fruitArt};
})();
